//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashDouble.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ethnicity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ethnicity()
        {
            this.Profiles = new HashSet<Profile>();
        }
    
        public int EthnicityID { get; set; }
        public Nullable<bool> Asian { get; set; }
        public Nullable<bool> African { get; set; }
        public Nullable<bool> Caucasian { get; set; }
        public Nullable<bool> EasternEurope { get; set; }
        public Nullable<bool> EastIndian { get; set; }
        public Nullable<bool> Hispanic { get; set; }
        public Nullable<bool> MiddleEastern { get; set; }
        public Nullable<bool> NativeAmerican { get; set; }
        public Nullable<bool> PacificIslander { get; set; }
        public Nullable<bool> Other { get; set; }
        public Nullable<bool> NoAnswer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile> Profiles { get; set; }
    }
}
