//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashDouble.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Genre()
        {
            this.Profiles = new HashSet<Profile>();
        }
    
        public int GenreID { get; set; }
        public Nullable<bool> Acting { get; set; }
        public Nullable<bool> Art { get; set; }
        public Nullable<bool> Bodypaint { get; set; }
        public Nullable<bool> Cosplay { get; set; }
        public Nullable<bool> Dance { get; set; }
        public Nullable<bool> Editorial { get; set; }
        public Nullable<bool> Erotic { get; set; }
        public Nullable<bool> Fashion { get; set; }
        public Nullable<bool> Fetich { get; set; }
        public Nullable<bool> FitModeling { get; set; }
        public Nullable<bool> Fitness { get; set; }
        public Nullable<bool> Glamour { get; set; }
        public Nullable<bool> HairMakeup { get; set; }
        public Nullable<bool> Lifestyle { get; set; }
        public Nullable<bool> Lingerie { get; set; }
        public Nullable<bool> PinUp { get; set; }
        public Nullable<bool> Pregnancy { get; set; }
        public Nullable<bool> Promotional { get; set; }
        public Nullable<bool> Runway { get; set; }
        public Nullable<bool> SpokespersonHost { get; set; }
        public Nullable<bool> Sports { get; set; }
        public Nullable<bool> Stunts { get; set; }
        public Nullable<bool> Swimwear { get; set; }
        public Nullable<bool> Underwater { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile> Profiles { get; set; }
    }
}
