//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashDouble.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPost
    {
        public int JobPostID { get; set; }
        public string JobTitle { get; set; }
        public string JobLocationCity { get; set; }
        public string JobLocationState { get; set; }
        public string JobLengthInDays { get; set; }
        public string JobDescription { get; set; }
        public int CompanyProfileID { get; set; }
    
        public virtual CompanyProfile CompanyProfile { get; set; }
    }
}
