//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashDouble.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int ProfileID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AgeRange { get; set; }
        public int Height { get; set; }
        public int Weight { get; set; }
        public Nullable<int> Bust { get; set; }
        public Nullable<int> Waist { get; set; }
        public string Dress { get; set; }
        public Nullable<int> Hips { get; set; }
        public Nullable<int> Cup { get; set; }
        public double Shoe { get; set; }
        public string ProfilePictureURL { get; set; }
        public string ProfileVideoURL { get; set; }
        public int EthnicityID { get; set; }
        public int GenreID { get; set; }
        public int ExperienceID { get; set; }
        public int GenderID { get; set; }
    
        public virtual Ethnicity Ethnicity { get; set; }
        public virtual Experience Experience { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
